### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by tobsn** [webbgeorge/php-sqs-tutorial#1]
This is the only single source of an actual working v3 example for SQS in PHP. Holy shit... :+1:

**Comment by webbgeorge** [comment]
Haha, no problem :). Let me know if you have any issues with it at all. P.s. I have several other articles on php development on my blog at http://george.webb.uno/

**Comment by tobsn** [comment]
@gaw508 this examples on sqs is just priceless... I swear I was looking around for days and couldn't find anything remotely useful.
