### ISSUE TITLE
About worker

### ISSUE THREAD

**Issue by dilab** [webbgeorge/php-sqs-tutorial#2]
Thanks for the great tutorial.

It is very useful for getting started with SQS in PHP.

One question though.

I am a bit concern of the worker, it is essentially running a never ending PHP script. 
Is that the only way of using worker with SQS?

**Comment by webbgeorge** [comment]
No problem at all, I'm happy it's helping. :)

Yes, that's right, so it can continuously monitor the queue for any new jobs, and process them with as little delay as possible. There is nothing wrong with having a php process running continuously, however, you may want to put some monitoring in place to make sure if it dies, the process is restarted, or if jobs stop being processed, you restart / add new worker processes.

If you still aren't comfortable with the idea of having a php process running like this, there are a couple of other options:
- Having the worker start on a minutely cron job, so the worker continues running until it runs out of jobs then quitting (you'll need to make some modifications to worker.php). This has the danger of having multiple processes running at any one time, but only if there are a lot of unprocessed jobs in the queue, however measures can be put in place to prevent this.
- Running the worker as a Daemon: http://stackoverflow.com/questions/2036654/run-php-script-as-daemon-process

**Comment by dilab** [comment]
Thanks for the clarification.

Running the worker as a Daemon seems like a logic choice. 
So that we can keep the worker running continuously after we exist the SSH session.

**Comment by webbgeorge** [comment]
No problem. Let me know if you have any more queries.
